### ISSUE TITLE
Better support for Bootstrap.

### ISSUE THREAD

**Issue by jorgeepena** [kondasoft/ks-bootshop#102]
The theme has alot of unique clases that modify the base boostrap file. Would be positive to depend solely on bootstrap to enhance the personalization via custom.css file.

Ex:
Using "col-desktop-3" gives the element 16% width that is not consistent with boostraps original "col-md-3" that would give you 33% width. And theres a class called "rows-col-3" that does have the 33% width but the usage is not clear.

**Comment by alvinkonda** [comment]
Hi Jorge,

You are right, we have modified a bit the bootstrap scss codes which you can check here
https://github.com/kondasoft/ks-bootshop/blob/master/src/bootstrap.scss

The most important changes are the spacing utiliies`p-`, `m-` and the responsive utilities (grid-breakpoints) that you have mentioned above, and that's because we think the theme performs better that way. But since we provide the bootstrap source file you may adjust those options if you prefer so. 

Let me know if you have additional questions about this.
